### PR TITLE
Merge space fight

### PR DESCRIPTION
**Pull request by RealJohnSmith**
Merge the space-fight thing to real master.

Lets try again. This time when I request review I want a review. Not just someone to click that "Merge" button. If I wanted that, I could do it myself

### CODE REVIEW

**Review by derekpock — CHANGES_REQUESTED** [review]
You wanted a review so here you go. We don't have time at this point to do a 100% code review, but I'll look over the code for some obvious potential issues, as well as some minor testing.

- Comments
  - Missing some indentations throughout. That's okay. Consistency is important but at this point its low priority.
  - Changes to the planet levels is generally NOT okay. This should be done as a separate commit in planet_levels (or maybe master at this point). The change is small enough for now.
  - Classes need documentation, but this is lower priority. Some are confusing what they do / used for initially.
  - Documentation across the entire project is typically inconsistent - just a note. Not specific to this merge.
  - Singletons are messy. I'd avoid this in future projects. They are good in some cases, but they typically point to an inherit design flaw (which is typically very difficult to fix). This could be argued, but just a note.
  - Missing lots of function documentation. That's...okay...at this point.
  - Throwing some exceptions (such as in a non-overridden render function) is okay but is typically only used in debugging. I'd have to think about this more in a fuller review.

- Suggested changes
  - Ducks spawn way too many sometimes - impossible to move or die. Add a limit.
  - I wish there was a way to abort the mission (travel back in time before making the decision) but this would involve more communication with the over-world. Consider it.

- Necessary changes
  - Credits for images? **This is necessary.** A text file with links (in the dist/resources/space folder) is enough.
  - Instructions are not intuitive - how do I finish? Add some flavor text "kill all enemies and reach the green portal" is enough. At this point it doesn't need to look good, but it is necessary. I died about 20 times and looked at the code before I could figure it out.

**Comment by derekpock** [comment]
@RealJohnSmith Consider joining the Slack channel (link in canvas), I'm up for conversation there if necessary, and I get notification from that easier than github.

**Comment by RealJohnSmith** [comment]
> Missing some indentations throughout. That's okay. Consistency is important but at this point its low priority.

Are you kidding me? Rest of your code doesnt even work. Naming conventions? Nothing. Informative commit messages? Nothing.

> Changes to the planet levels is generally NOT okay. This should be done as a separate commit in planet_levels (or maybe master at this point). The change is small enough for now.

That is exactly why I made extra commit and PR just for that. It got merged in by someone else. Also, in master should be only working things, but at the state I found it it wasn't even possible to run it.

> Missing lots of function documentation

Most of the functions are private, but JS does not have any private keyword or something. No documentation on these functions is OK.


> Credits for images? This is necessary. A text file with links (in the dist/resources/space folder) is enough.

Our images are CC-0 licensed. I can provides links anyway, but it is not required by the license


> Instructions are not intuitive. 

Yes, you are right. The winning was kind of hacked in. On the other hand at least controls and intuitive and goal (you are supposed to shoot enemies and all that). You cant say that about any other planet game (those that don't crash)

**Comment by ksu-shanemat** [comment]
> Are you fucking kidding me? Rest of your code doesnt even work. Naming conventions? Nothing. Informative commit messages? Nothing.
> 
> * Changes to the planet levels is generally NOT okay. This should be done as a separate commit in planet_levels (or maybe master at this point). The change is small enough for now.
> 
> That is exactly why I made extra commit and PR just for that. It got merged in by someone else. Also, in master should be only working things, but at the state I found it it wasn't even possible to run it.
> 
> * Missing lots of function documentation
> 
> Most of the functions are private, but JS does not have any private keyword or something. No documentation on these functions is OK.
> 
> * Credits for images? This is necessary. A text file with links (in the dist/resources/space folder) is enough.
>   Our images are CC-0 licensed. I can provides links anyway, but it is not required by the license
> * Instructions are not intuitive. Yes, you are right. The winning was kind of hacked in. On the other hand at least controls and intuitive and goal (you are supposed to shoot enemies and all that). You cant say that about any other planet game (those that don't crash)

**Comment by ksu-shanemat** [comment]
Sorry guys, accidentally hit wrong button :// (Wish there was some confirmation before closing PR)

**Comment by RealJohnSmith** [comment]
> I wish there was a way to abort the mission (travel back in time before making the decision) but this would involve more communication with the over-world. Consider it.

I don't believe that is possible at this point, because whenever our game finishes, it just continues travelling to the next planet

**Comment by RealJohnSmith** [comment]
> Instructions are not intuitive.

My last commit should fix that

**Review by ksu-shanemat — APPROVED** [review]

**Comment by derekpock** [comment]
> > Missing some indentations throughout. That's okay. Consistency is important but at this point its low priority.
> 
> Are you kidding me? Rest of your code doesnt even work. Naming conventions? Nothing. Informative commit messages? Nothing.

I'm not kidding you. I didn't say our planet side was spotless. Our code is working. I've done extensive documentation on my part and kept indentation consistent. All of my commits are informative. I didn't write all the planet levels, and I'm not expecting others to have the same level of thoroughness that I did, we simply don't have time for it. I wouldn't get defensive here, either. I looked at your code from an objective standpoint, regardless of how the rest of the project is looking, as it should be. If you didn't want comments like these, then why the PR? Aside from trying to test people, that is. You shouldn't compare yourself to others in a git-project, in the real world if you say "well person B's code looks awful, that's why I didn't do X," that will get you fired pretty quickly, let alone setting the mood for your team.

> > Changes to the planet levels is generally NOT okay. This should be done as a separate commit in planet_levels (or maybe master at this point). The change is small enough for now.
> 
> That is exactly why I made extra commit and PR just for that. It got merged in by someone else. Also, in master should be only working things, but at the state I found it it wasn't even possible to run it.

I appreciate the "test" of our "extensive" PR system, but it really isn't necessary right now. When I tested the master (not sure if it was the same time), it was running for me. Not sure what changed, doesn't matter now.

> > Missing lots of function documentation
> 
> Most of the functions are private, but JS does not have any private keyword or something. No documentation on these functions is OK.

Private functions should still be documented, what if a feature is broken / needs updated? Someone goes in and sees a bunch of private classes with no documentation and is at a loss of how it works.

> > Credits for images? This is necessary. A text file with links (in the dist/resources/space folder) is enough.
> 
> Our images are CC-0 licensed. I can provides links anyway, but it is not required by the license

Okay I wasn't sure. A link might be nice, but just wanted to make sure you thought of this.

> > Instructions are not intuitive.
> 
> Yes, you are right. The winning was kind of hacked in. On the other hand at least controls and intuitive and goal (you are supposed to shoot enemies and all that). You cant say that about any other planet game (those that don't crash)

Again I didn't make the planet levels, that's other people working individually. If we had another week and half of the students didn't decide to start at the last minute after I repeatedly told them to push stuff earlier for testing, we wouldn't be here, but here we are. We'll have to make the best of what we have.

> > I wish there was a way to abort the mission (travel back in time before making the decision) but this would involve more communication with the over-world. Consider it.
> 
> I don't believe that is possible at this point, because whenever our game finishes, it just continues travelling to the next planet

That's alright. I expected that.

I haven't looked at the instructions but I'll trust they look decent.

**Review by derekpock — APPROVED** [review]

**Comment by derekpock** [comment]
Saw the message, looks nice. I'm gonna go ahead and merge everything.

**Pull request merged**
